/**
 * `useMemoCache(size)` — React Compiler hook.
 *
 * This hook is emitted by the React Compiler (React Forget) to cache
 * memoized values. It returns an array of `size` slots that the compiler
 * uses to store and retrieve memoized computations.
 *
 * In environments without the React Compiler, this hook simply returns a
 * new array of `undefined` values — it has no observable side effects.
 *
 * ```ts
 * // Generated by React Compiler:
 * const $ = useMemoCache(4);
 * if ($[0] !== props.value) {
 *   $[0] = props.value;
 *   $[1] = expensiveComputation(props.value);
 * }
 * const result = $[1];
 * ```
 *
 * @param size - Number of cache slots to allocate.
 * @returns An array of `size` undefined slots.
 *
 * @public
 */
export function useMemoCache(size: number): Array<unknown> {
	// In Lua, we allocate a table with `size` entries.
	// Without the React Compiler, this is just a pre-allocated array.
	const cache: Array<unknown> = [];
	for (let i = 0; i < size; i++) {
		cache[i] = undefined;
	}
	return cache;
}
